In [ ]:
import numpy as np
blank_arr = np.array([])
print("Blank Array: ", blank_arr)

arr_zero = np.zeros(5)
print('Array of zeros:',arr_zero)


Blank Array:  []
Array of zeros: [0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
arr1 = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])

print("Array with Predefined Data: ", arr)
print("Array with Pattern Specific Data: \n", arr1)

Array with Predefined Data:  [10 20 30 40 50 60 70 80 90]
Array with Pattern Specific Data: 
 [[10 20 30 40]
 [50 60 70 80]]


In [ ]:
# Array Slicing of 1D array
a1 = arr[:2]
a2 = arr[5:]
a3 = arr[2:5]

print("Array 1: ", a1)
print("Array 2: ", a2)
print("Array 3: ", a3)

Array 1:  [10 20]
Array 2:  [60 70 80 90]
Array 3:  [30 40 50]


In [ ]:
# Array Slicing of 2D array
a4 = arr1[:,1]
a5 = arr1[1,:]
a6 = arr1[0,3]

print("Array 4: ", a4)
print("Array 5: ", a5)
print("Specific Element: ", a6)

Array 4:  [20 60]
Array 5:  [50 60 70 80]
Specific Element:  40


In [ ]:
# Updating Array
arr[0] = 100
print("Updated 1D array: ", arr)

arr1[1][3] = 20
print("Updated 2D array: \n", arr1)

Updated 1D array:  [100  20  30  40  50  60  70  80  90]
Updated 2D array: 
 [[10 20 30 40]
 [50 60 70 20]]


In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

print("Array 2: \n", arr2)
print("Shape of array: ", arr2.shape)

Array 2: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of array:  (4, 3)


In [ ]:
# Reshaping of Array
arr_reshape = arr2.reshape(3, 4)
print("Array after reshaping to dimension (3, 4): \n", arr_reshape)

arr_reshape2 = arr2.reshape(-1)
print("\nArray after reshaping to one dimension: \n", arr_reshape2)

Array after reshaping to dimension (3, 4): 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array after reshaping to one dimension: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Looping over Array
print("Array 1: ", arr)

for i in range(len(arr)):
  print(f"a[{i}]: {arr[i]}")

Array 1:  [10 20 30 40 50 60 70 80 90]
a[0]: 10
a[1]: 20
a[2]: 30
a[3]: 40
a[4]: 50
a[5]: 60
a[6]: 70
a[7]: 80
a[8]: 90


In [ ]:
i = 0
print("Elements of even indexes: ")

while i < len(arr):
    print(f"a[{i}]: {arr[i]}")
    i += 2

Elements of even indexes: 
a[0]: 10
a[2]: 30
a[4]: 50
a[6]: 70
a[8]: 90


In [ ]:
# Reading file
file_data = np.loadtxt("data2.txt", dtype=str)
print(file_data)

[['Parikshit' '07' '2003']
 ['Stephen' '03' '1990']
 ['Rohit' '45' '1987']]


In [ ]:
data = np.genfromtxt("data1.csv", dtype=str,
                     encoding=None, delimiter=",")
print(data)

[['Parikshit' 'CSE-A' '303']
 ['Vaibhav' 'CSE-A' '287']
 ['Priyansh' 'CSE-A' '285']]
